### PR TITLE
 typeScript homework

### PR DESCRIPTION
**Pull request by nevensh**
hey Elias .
I have solved  some Questions in typescript . 
please check it to do merge.
and I tried to put semantic commits on the push line But it didn't work.

### CODE REVIEW

**Comment by EliasSalom** [comment]
you have been opening a pull request without my name on the Reviewers, which means I will never know that you do something, I will put myself and start the review
@nevensh

**Review by EliasSalom — CHANGES_REQUESTED** [review]
`node_modules` is here, and I asked never upload `node_modules`

**Comment by nevensh** [comment]
hey elias i tried to put node_modules in .gitignore but it didn't move . 
i put it as you put it A few weeks ago. 
And also with you the node-modules didn't move to gitignore.
i hope to repeat it  today on the zoom meeting.
thank you .

**Comment by EliasSalom** [comment]
I will, thank you for your replay

**Comment by EliasSalom** [comment]
now you know how to handle it, can you try to fix this issue?

**Comment by nevensh** [comment]
hey elias , i handle it .
please check it.
thank you

**Pull request closed without merging**
